server:
  port: 9001

spring:
  # Database (MySQL) Settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
    username: taelim0619
    password: a1234
# Mybatis Settings
mybatis:
  type-aliases-package: thyme.data.mapper
  mapper-locations: classpath:mapper/**/*.xml