server:
 port: 9000
#mysql_setting
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
   username: taelim0619
   password: a1234
#jsp_setting
 devtools:
   livereload:
     enabled: true
#mybats
mybatis:
  type-aliases-package: boot.data.dto
  mapper-locations:
  - /mapper/**/*.xml
